src/Entity/Parcel.php
<?php

namespace App\Entity;

use App\Repository\ParcelRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ParcelRepository::class)
 */
class Parcel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $gps_location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $region;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGpsLocation(): ?int
    {
        return $this->gps_location;
    }

    public function setGpsLocation(int $gps_location): self
    {
        $this->gps_location = $gps_location;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }
}

src/Form/ParcelType.php
<?php

namespace App\Form;

use App\Entity\Parcel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParcelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('gps_location')
            ->add('region')
            ->add('country')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Parcel::class,
        ]);
    }
}

src/Controller/ParcelController.php
<?php

namespace App\Controller;

use App\Entity\Parcel;
use App\Form\ParcelType;
use App\Repository\ParcelRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/parcel")
 */
class ParcelController extends AbstractController
{
    /**
     * @Route("/", name="parcel_index", methods={"GET"})
     */
    public function index(ParcelRepository $parcelRepository): Response
    {
        return $this->render('parcel/index.html.twig', [
            'parcels' => $parcelRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="parcel_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $parcel = new Parcel();
        $form = $this->createForm(ParcelType::class, $parcel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($parcel);
            $entityManager->flush();

            return $this->redirectToRoute('parcel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('parcel/new.html.twig', [
            'parcel' => $parcel,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="parcel_show", methods={"GET"})
     */
    public function show(Parcel $parcel): Response
    {
        return $this->render('parcel/show.html.twig', [
            'parcel' => $parcel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="parcel_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Parcel $parcel, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ParcelType::class, $parcel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('parcel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('parcel/edit.html.twig', [
            'parcel' => $parcel,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="parcel_delete", methods={"POST"})
     */
    public function delete(Request $request, Parcel $parcel, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$parcel->getId(), $request->request->get('_token'))) {
            $entityManager->remove($parcel);
            $entityManager->flush();
        }

        return $this->redirectToRoute('parcel_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/parcel/_delete_form.html.twig
<form method="post" action="{{ path('parcel_delete', {'id': parcel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ parcel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/parcel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/parcel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Parcel{% endblock %}

{% block body %}
    <h1>Edit Parcel</h1>

    {{ include('parcel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('parcel_index') }}">back to list</a>

    {{ include('parcel/_delete_form.html.twig') }}
{% endblock %}

templates/parcel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parcel index{% endblock %}

{% block body %}
    <h1>Parcel index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Gps_location</th>
                <th>Region</th>
                <th>Country</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for parcel in parcels %}
            <tr>
                <td>{{ parcel.id }}</td>
                <td>{{ parcel.gpsLocation }}</td>
                <td>{{ parcel.region }}</td>
                <td>{{ parcel.country }}</td>
                <td>
                    <a href="{{ path('parcel_show', {'id': parcel.id}) }}">show</a>
                    <a href="{{ path('parcel_edit', {'id': parcel.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('parcel_new') }}">Create new</a>
{% endblock %}

templates/parcel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Parcel{% endblock %}

{% block body %}
    <h1>Create new Parcel</h1>

    {{ include('parcel/_form.html.twig') }}

    <a href="{{ path('parcel_index') }}">back to list</a>
{% endblock %}

templates/parcel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parcel{% endblock %}

{% block body %}
    <h1>Parcel</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ parcel.id }}</td>
            </tr>
            <tr>
                <th>Gps_location</th>
                <td>{{ parcel.gpsLocation }}</td>
            </tr>
            <tr>
                <th>Region</th>
                <td>{{ parcel.region }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ parcel.country }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('parcel_index') }}">back to list</a>

    <a href="{{ path('parcel_edit', {'id': parcel.id}) }}">edit</a>

    {{ include('parcel/_delete_form.html.twig') }}
{% endblock %}